### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by ChuxiJ** [hci-unihd/mutex-watershed#2]
when I run python setup.py install, I get:
running install
running bdist_egg
running egg_info
writing mutex_watershed.egg-info/PKG-INFO
writing dependency_links to mutex_watershed.egg-info/dependency_links.txt
writing requirements to mutex_watershed.egg-info/requires.txt
writing top-level names to mutex_watershed.egg-info/top_level.txt
reading manifest file 'mutex_watershed.egg-info/SOURCES.txt'
writing manifest file 'mutex_watershed.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
gcc -pthread -B /opt/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/anaconda3/include/python3.7m -c /tmp/tmph205w3zf.cpp -o tmp/tmph205w3zf.o -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
gcc -pthread -B /opt/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/anaconda3/include/python3.7m -c /tmp/tmpmpj2kmxf.cpp -o tmp/tmpmpj2kmxf.o -fvisibility=hidden
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
building 'mutex_watershed' extension
creating build
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/src
gcc -pthread -B /opt/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/anaconda3/include/python3.7m -I/home/jupyter/.local/include/python3.7m -I/opt/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/opt/anaconda3/include -I/opt/anaconda3/Library/include -I/opt/anaconda3/include/python3.7m -c src/main.cpp -o build/temp.linux-x86_64-3.7/src/main.o -DVERSION_INFO="0.1.1" -std=c++14 -fvisibility=hidden
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
src/main.cpp:7:29: fatal error: xtensor/xmath.hpp: No such file or directory
 #include "xtensor/xmath.hpp"
                             ^
compilation terminated.
error: command 'gcc' failed with exit status 1

How can I fix it?

**Comment by constantinpape** [comment]
The compiler does not find `xtensor`.
Did you follow the steps described in [installation](https://github.com/hci-unihd/mutex-watershed#installation)?
If you did, your conda environment should contain `xtensor`. You can check this with `conda list`.

**Comment by ChuxiJ** [comment]
Thanks for the response, it works now!
I can run your code, but the results seem different. WE really want to reproduce your experiments.
![image](https://user-images.githubusercontent.com/30956809/60787225-6bf99680-a19c-11e9-8a42-e4a8c9867865.png)
![image](https://user-images.githubusercontent.com/30956809/60787348-dd394980-a19c-11e9-9f7f-45b7c27c4b45.png)

It seems that we need to do an extra edge detection process. Also, I found the result is not good as the paper says

**Comment by constantinpape** [comment]
Could you elaborate a bit? How did you obtain the images you show here. What experiments exactly did you run? 

> It seems that we need to do an extra edge detection process.

The mutex watershed will output a label image. It's trivial to translate this to an edge image, e.g. using [this functions](https://github.com/hci-unihd/mutex-watershed/blob/master/experiments/isbi/view_result.py#L7-L17).

> Also, I found the result is not good as the paper says

Based on which criterion? Note that the algorithm's quality depends on the input predictions, so improving network predictions is usually the best way to improve results.

**Comment by ChuxiJ** [comment]
![image](https://user-images.githubusercontent.com/30956809/60876339-12b66380-a27f-11e9-96aa-23e10925dc30.png)
Thanks, I know how it works now!!

**Comment by constantinpape** [comment]
> Thanks, I know how it works now!!

You're welcome. I am closing this for now, feel free to raise another issue if you have more questions.
