### ISSUE TITLE
data repository not reachable

### ISSUE THREAD

**Issue by erjel** [hci-unihd/mutex-watershed#4]
The link to
https://hcicloud.iwr.uni-heidelberg.de/index.php/s/6LuE7nxBN3EFRtL
does not work.

**Comment by constantinpape** [comment]
Yes, for some reason the link stopped working.
I have reuploaded the data and already update the link in the readme:
https://oc.embl.de/index.php/s/sXJzYVK0xEgowOz

**Comment by erjel** [comment]
Thank you for the quick reply 👍
